AppBundle\Entity\Product:
    properties:
        name: [ NotBlank: ~, Length: {min: 3} ]
        price: [ NotBlank: ~ ]
        description: [ NotBlank: ~ ]
        currentQuantity: [ NotBlank: ~ ]


AppBundle\Entity\Customer:
    properties:
        name: [ NotBlank: ~, Length: {min: 3}]
        email: [ NotBlank: ~, Email: ~]


AppBundle\Entity\Invoice:
    properties:
        customer: [ NotBlank: ~]
        items: [ Valid: ~]


AppBundle\Entity\InvoiceItem:
    properties:
        product: [ NotBlank: ~]
        quantity: [ NotBlank: ~, GreaterThan: {value: 0}]